### ISSUE TITLE
Mark location permissions with maxSdkVersion=30

### ISSUE THREAD

**Issue by nisrulz** [weliem/blessed-android-coroutines#10]
Location permissions are only required for API 30 and below. Marking those to be only for maxSdkVersion=30 should be part of the lib.

```xml
<uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION"
        android:maxSdkVersion="30" />
    <uses-permission
        android:name="android.permission.ACCESS_COARSE_LOCATION"
        android:maxSdkVersion="30" />
```

I already have a [branch with the changes](https://github.com/nisrulz/blessed-android-coroutines/commit/769595ec8d054e4eb4ecad81895511762ff4e96b), but wanted to open an issue to discuss if there are any blockers or questions.

**Comment by weliem** [comment]
Maybe it doesn't hurt. But why do you think it 'should be' part of the library? If you don't need it in your app you can just ignore it. What if somebody needs location permission for other reasons than bluetooth?

**Comment by nisrulz** [comment]
It is already part of the library. Let me clarify:

These permissions are part of lib AndroidManifest file:
```xml
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"  />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
```
i.e during Manifest Merger phase these are merged into the final AndroidManifest.xml file along with that of the app. Now based on current setup, this would mean that the app is now listing itself to be using Location permissions for all API levels (including 31+) when it actually doesn't need to because it only wants to use the Bluetooth scan functionality.

The core usecase of the lib is to provide Bluetooth functionality. Prior to API 31 the location permissions were required. Hence restricting the location permissions to API 30 and below will mean that they are not considered for API 31, but are respected in API 30 and below.

Note that you [already assert that location services](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location) are not to be used in the BLUETOOTH_SCAN permission by using `android:usesPermissionFlags="neverForLocation"`

```xml
<uses-permission
        android:name="android.permission.BLUETOOTH_SCAN"
        android:usesPermissionFlags="neverForLocation"
        tools:targetApi="s" />
```

**Comment by weliem** [comment]
Ok feel free to raise a PR

**Comment by SteveGrosbois** [comment]
Note that if you want to use location features in your app, you have to override `android:maxSdkVersion` flag with : 
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 
    tools:remove="android:maxSdkVersion" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
    tools:remove="android:maxSdkVersion" />
```

My suggestion if to remove all permissions from the AndroidManifest file of the lib and add some doc to explain what permissions to add on the app.

**Comment by nisrulz** [comment]
That is a valid point. Info about adding Location permissions should be part of integration docs. Rest permissions are related to Bluetooth only, so are fine to be part of lib's manifest file.

Edit: I could open a PR tonight, if we agree on the suggested solution.

**Comment by cren90** [comment]
@kwiky @nisrulz @weliem After fighting this for several hours before discovering the maxSdkVersion attribute on the permission in the Manifest Merge Blame. I am squarely in the camp of document the permissions needed and leave it out of the library. I know this is an old ticket so I'll open a new one if you guys agree

**Comment by martijnvanwelie** [comment]
So what exactly is going wrong? For most people this saves them from having to deal with Android permission hell....

To my knowledge, the permissions are correct with regards to BLE and the various Android requirements. Apart from that you can always overrule them in your app...

**Comment by SteveGrosbois** [comment]
> So what exactly is going wrong? For most people this saves them from having to deal with Android permission hell....

The issue i see is that is not the purpose of a library to include `uses-permissions` tags in the manifest.
And for a lot of other libraries or SDKs, the `uses-permissions` tags are not included, but the documentation mentions that you have to add it by yourself in your own Manifest.

Some examples (search for "permissions" on those docs) : 
- https://docs.mapbox.com/android/maps/guides/install/
- https://developer.here.com/documentation/android-sdk-lite/4.14.4.0/dev_guide/topics/quick-start.html#create-a-new-android-project
- https://developer.kontakt.io/docs/dev-ctr-sdks/ZG9jOjMwMzg3NjQ5-quickstart-setup#step-2-permissions
- etc...

> To my knowledge, the permissions are correct with regards to BLE and the various Android requirements. Apart from that you can always overrule them in your app...

The other issue is that, on the other hand, the blessed documentation did not mention that you have to remove maxSdkVersion in your own manifest if you plan to use Location API.


What ever is decided here, there is a lack of documentation, and some developers waste a lot of time discovering this issue.

**Comment by abdallahalaraby** [comment]
I just spent two days trying to figure out what's causing my app to not include the location permission when I already had added it to the app Manifest. The `tools:remove="android:maxSdkVersion"` MUST be added to the main Readme.md file

**Comment by NikitaLeontev** [comment]
> @kwiky @nisrulz @weliem After fighting this for several hours before discovering the maxSdkVersion attribute on the permission in the Manifest Merge Blame. I am squarely in the camp of document the permissions needed and leave it out of the library. I know this is an old ticket so I'll open a new one if you guys agree

I spent 3 hours to solve the problem, please return my 3 hours drained into the trash

**Comment by weliem** [comment]
This issue was already fixed a while ago. Also the Read.me was upated. 

Are you on the latest version of this library?

**Comment by NikitaLeontev** [comment]
The application uses a location, after including the library in the build, when checking the location, the activity is recreated
Аfter the merge, the manifest contains a limit of 30 sdks, which breaks the normal operation of the application
@kwiky the solution works, but to understand what the problem is when adding a library, you need to spend time
https://github.com/weliem/blessed-android-coroutines/blob/main/app/src/main/AndroidManifest.xml (manifest has a limit of 30sdk for location)

**Comment by nisrulz** [comment]
You are pointing to the permissions defined in the [sample app](https://github.com/weliem/blessed-android-coroutines/blob/main/app/src/main/AndroidManifest.xml) and not the [library module](https://github.com/weliem/blessed-android-coroutines/blob/main/blessed/src/main/AndroidManifest.xml). 

The one from the library module get merged into the YOUR app when you add a dependency on the library i.e

```xml
<!-- Needed only if code looks for Bluetooth devices.
         Since the code doesn't use Bluetooth scan results to derive physical
         location information, it is strongly asserted that the code
         doesn't derive physical location.
         Link:
     https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location
         -->
     <uses-permission
          android:name="android.permission.BLUETOOTH_SCAN"
          android:usesPermissionFlags="neverForLocation"
          tools:targetApi="s" />

     <!-- Needed only if code communicates with already-paired Bluetooth
         devices. -->
     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

     <!-- Needed only if code makes the device discoverable to Bluetooth
         devices. -->
     <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
```
**Note that none of these have the `android:maxSdkVersion="30"` set on them. `tools:targetApi="s"` is for helping the IDE.**

The app module in this repo is for demonstrating the usage of the library module. The information to use the extra permissions is [in the readme of this repo](https://github.com/weliem/blessed-android-coroutines/tree/main?tab=readme-ov-file#adding-permissions). The documentation is actually clear. The reason you are having an issue is because you are literally copy pasting the code in the Readme rather than use logic about why you need the permission set in this certain way. [Google has good documentation about this](https://developer.android.com/develop/connectivity/bluetooth/bt-permissions#declare-android12-or-higher).

At the very least the documentation can be updated to mention the 2 usecases i.e one where your app needs location permission as a feature + bluetooth and one where you only need it for bluetooth. 

I hope that clarifies how to use the library.

**Comment by NikitaLeontev** [comment]
indeed, there is no such problem on the latest version, I had a branch written more than a year ago with version 0.3.2, and now when installing on a modern phone there was the problem described above
