### ISSUE TITLE
Release name is wrong

### ISSUE THREAD

**Issue by nisrulz** [weliem/blessed-android-coroutines#12]
I think it is supposed to be v0.1.3, unless there is a missing tag of 0.1.4 and the tag 0.1.3 got overwritten or something.

<img width="969" alt="Screenshot 2021-11-29 at 13 02 54" src="https://user-images.githubusercontent.com/2096087/143864929-0d642328-ad22-4665-b5f7-8b55bb154ad3.png">
<img width="581" alt="Screenshot 2021-11-29 at 13 03 21" src="https://user-images.githubusercontent.com/2096087/143864935-48605669-254e-46ea-8379-0a64da6b6b72.png">

**Comment by weliem** [comment]
ooops, typo....but shouldn't cause any harm

**Comment by nisrulz** [comment]
True. I was just confused and decided to build from last commit from Jitpack thinking there is a tag missing.
