### ISSUE TITLE
Trying to get 16 byte from Characteristic but ouputs only zeros

### ISSUE THREAD

**Issue by AkroBJ** [weliem/blessed-android-coroutines#14]
I can can read from this characteristics in the NRF app as well as using the flutter_blue library, which we used for an older app before.

I'm using this code to read from a characteristic.

```
peripheral.getCharacteristic(SERVICE_UUID, NOTIFICATION_UUID)?.let {
   val test = peripheral.readCharacteristic(it)
   Timber.d("${test.size}")
   Timber.d("${test.asList()}")
}
```

As output, I only get zeros

```
/BluetoothPeripheral: reading characteristic <0000ff01-0000-1000-8000-00805f9b34fb>
D/BluetoothHandler: 16
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

That am I missing? I tried it on Android 11 and on an old Android 9 phone with the same result both times

**Comment by AkroBJ** [comment]
I tried the BLESSED Java library as well now and it works. So there is a bug with this library. I'll hope we can find it and fix it as I would prefer to use this one :)

**Comment by weliem** [comment]
The same code runs fine in the test app of this library. Looks like your peripheral is really returning 16 zeros...

**Comment by AkroBJ** [comment]
No, I also programmed the peripheral.

It works with the flutter_blue library on Dart and with the Java version of your library BLESSED as well as on nRF and Windows. Was there an update recently that it might work now? I tried the Jetpack 0.2.1 version

**Comment by martijnvanwelie** [comment]
The code for a readCharacteristic is very straightforward and since you are getting a byte array of the right length, I don't understand what could be going wrong. Especially since it works in my demo app...

Is there anything you can share to debug this issue? What's you code? Can you share a log?
