### ISSUE TITLE
Wrong implementation of bytesToFloat

### ISSUE THREAD

**Issue by fcolasuonno** [weliem/blessed-android-coroutines#16]
Hello, I receive wrong values when trying to read a FORMAT_FLOAT as shown by this test

```kotlin
package com.welie.blessed

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.ByteBuffer
import java.nio.ByteOrder

class BluetoothBytesParserTest {

    @Test
    fun getFloatValueLE() {
        val byteParser = BluetoothBytesParser(
            ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN).putFloat(1.1f).array(),
            ByteOrder.LITTLE_ENDIAN
        )
        assertEquals(byteParser.getFloatValue(BluetoothBytesParser.FORMAT_FLOAT), 1.1f)
    }

    @Test
    fun getFloatValueBE() {
        val byteParser = BluetoothBytesParser(
            ByteBuffer.allocate(4).order(ByteOrder.BIG_ENDIAN).putFloat(1.1f).array(),
            ByteOrder.BIG_ENDIAN
        )
        assertEquals(byteParser.getFloatValue(BluetoothBytesParser.FORMAT_FLOAT), 1.1f)
    }

    @Test
    fun setFloatValueLE() {
        val byteParser = BluetoothBytesParser(ByteArray(4), ByteOrder.LITTLE_ENDIAN)
        val floatValue = byteParser.setFloatValue(1.1f, BluetoothBytesParser.FORMAT_FLOAT)
        assertTrue(floatValue)
        assertEquals(ByteBuffer.wrap(byteParser.value).order(ByteOrder.LITTLE_ENDIAN).float, 1.1f)
    }

    @Test
    fun setFloatValueBE() {
        val byteParser = BluetoothBytesParser(ByteArray(4), ByteOrder.BIG_ENDIAN)
        val floatValue = byteParser.setFloatValue(1.1f, BluetoothBytesParser.FORMAT_FLOAT)
        assertTrue(floatValue)
        assertEquals(ByteBuffer.wrap(byteParser.value).order(ByteOrder.BIG_ENDIAN).float, 1.1f)
    }
}
```

**Comment by weliem** [comment]
The code works fine. But I assume you are seeing the typical rounding issues with floats. A value like 1.1 may become 1.0999 after conversion.

**Comment by fcolasuonno** [comment]
Sorry, can you try again? The value I get when running the test are -Infinity, -Infinity, -1.3421772E8, -1.3421772E8 instead of 1.1. Also when reading from a peripheral I get -Infinity, but if I use an online converter like https://www.h-schmidt.net/FloatConverter/IEEE754.html o ByteBuffer.wrap I get the correct value

**Comment by weliem** [comment]
BLE uses IEEE 11073 encoding for floats and not IEEE 754. See for example: https://stackoverflow.com/questions/60841331/dart-convert-ieee-11073-32-bit-float-to-a-simple-double

ByteBuffer uses IEEE 754 so that is why you are seeing the issues...

**Comment by fcolasuonno** [comment]
Thank you, that clarifies my confusion a lot.
I think the standard specifies that both encodings could be used https://btprodspecificationrefs.blob.core.windows.net/assigned-numbers/Assigned%20Number%20Types/Format%20Types.pdf but 11073 is the preferred one for medical devices. Mine is not a medical device, but just an arduino nano sending some floats through BLE.
Thank you again
