### ISSUE TITLE
How to auto connect BLE device when in range in background?

### ISSUE THREAD

**Issue by mmswide** [weliem/blessed-android-coroutines#33]
Is there a way to auto connect BLE device in background when the app is in the background?

**Comment by weliem** [comment]
The method autoConnectPeripheral() will work as long as the app is running. If your app gets killed often you need to use a ForegroundService....

**Comment by mmswide** [comment]
Thank you. I will try.

**Comment by mmswide** [comment]
I created foreground service and startScan in background task.
But I could get any response from BluetoothCentralManagerCallback.
Would you please help me how I can get this callback from startScan in background?

**Comment by weliem** [comment]
I think your question is going beyond the scope of this library, so I am closing the issue
