### ISSUE TITLE
Not detecting  Heart Rate Sensor (0x180D)-> When when scanning with Service

### ISSUE THREAD

**Issue by droideveloper1996** [weliem/blessed-android-coroutines#35]
I am trying to find my device using the following code 
  var deviceMap = HashMap<String, BluetoothPeripheral>()
 val HEART_RATE_NOTIFY_SERVICE_UUID = UUID.fromString("0000180d-0000-1000-8000-00805f9b34fb")
 val WEIGHT_SCALE_SERVICE = UUID.fromString("0000181d-0000-1000-8000-00805f9b34fb")
        var list = arrayOf<UUID>(
            WEIGHT_SCALE_SERVICE,
             HEART_RATE_NOTIFY_SERVICE_UUID
        )
centralManager.scanForPeripheralsWithServices(list, { peripheral, scanResult ->
            Log.d("Device", peripheral.address)
            deviceMap.put(peripheral.address, peripheral)
        }, { error ->
        })

It is able to detect weight scale but not detecting heart rate.

**Comment by weliem** [comment]
Are you sure your device is advertising the heartrate service? Use nrfConnect to verify
