### ISSUE TITLE
NullPointerException in BluetoothPeripheralManager

### ISSUE THREAD

**Issue by cren90** [weliem/blessed-android-coroutines#36]
Looks like the BluetoothPeripheralManager does not handle null device names well in the `handleDeviceConnected` function. Looks like the line linked below is the culprit for this case, but I think others will fail similarly.

https://github.com/weliem/blessed-android-coroutines/blob/678b4ebeb249d65382790ba3eb8f0f0aaf132459/blessed/src/main/java/com/welie/blessed/BluetoothPeripheralManager.kt#L91

![Stacktrace](https://user-images.githubusercontent.com/24256190/226716596-b5e956b5-0e88-4438-9c92-f5cd9e40d486.png)

**Comment by cren90** [comment]
I think for a change, something like 
`Logger.i(TAG, "Central '%s' (%s) connected", device.name ?: "null", device.address)`

I'm happy to put up a PR with the change(s?) but wanted to get thoughts/other options first

**Comment by weliem** [comment]
Good catch, I am happy to accept a PR with your suggestion....

**Comment by cren90** [comment]
@weliem I've created a branch but I'm unable to push (403 error), looks like I don't have permissions. I've also made the same change for https://github.com/weliem/blessed-android/issues/181 on the non-coroutines repo, with the same issue pushing.

**Comment by cren90** [comment]
@weliem Any thoughts?

**Comment by weliem** [comment]
Normally with Github you have to make a fork first and then do PR....

anyway, did the fix for you and made a new release: 0.3.3

**Comment by cren90** [comment]
@weliem Found another instance of this one. Posted https://github.com/weliem/blessed-android-coroutines/pull/38 to fix
