### ISSUE TITLE
Any chance to lower minSdk to 23?

### ISSUE THREAD

**Issue by izvansvemirac** [weliem/blessed-android-coroutines#4]
Not an issue - more of a nice to have

**Comment by weliem** [comment]
Considering the latest is now 31, I don't have any interest in lowering the minSdk. I also wanted to make sure we are at least on Java 8, so that rules out 23....

**Comment by izvansvemirac** [comment]
Was there any specific reason for having it set to 26 (API usage or something similar?)
I'd be happy to create a PR with it as does not seem to conflict with anything currently.
Just wanted to point out that targetSdk can and should still point to current API level and we're also using Java 8 in our project and we are just dropping support for 17 😄 .
Thanks in any case.

**Comment by weliem** [comment]
I think Java 8 is only available as of sdk 26 and there are also some BLE bugs I didn't want to deal with. As of 26 BLE started working quite well...

This library might still work on 23....

**Comment by izvansvemirac** [comment]
It does work for 23 too, it just requires me to do an android manifest ignore for this lib.
