### ISSUE TITLE
compose ui

### ISSUE THREAD

**Issue by mordeshen** [weliem/blessed-android-coroutines#40]
Has Blessed been tested on Compose UI?

**Comment by weliem** [comment]
Not sure what you mean. This is a BLE library that has nothing to do with any UI framework....

**Comment by mordeshen** [comment]
Thanks, I mean, I tried to work with the library and everything went very well, but when I changed just the UI from view to Compose, the changes of the data from the device(onCharacteristicChanged) didn't receive. tried a couple of ways(lifecycles stuff mainly), and because I didn't really try to dive into the library, I wondered if this strange case, as u said, tested.

**Comment by weliem** [comment]
I can't think of a reason why it wouldn't work in Compose. Just make sure you don't mess up the threading part...

**Comment by mordeshen** [comment]
thanks. appreciate your work!
