### ISSUE TITLE
observeConnectionState - 5 second delay

### ISSUE THREAD

**Issue by bmartinezdev** [weliem/blessed-android-coroutines#41]
Hi, First off, Thank you for writing this library.  It has made dealing with BLE a much better experience.

My question is, is there a faster way to get feedback from observeConnectionState?
I have a total of 6 BLE devices that I am connected to and my requirement is to stop all of the connections if any of the devices gets disconnected.

The callback works great and I am able to disconnect all of the devices if 1 becomes disconnected but there's about a 5 second delay from when I pull the battery off 1 device until the time the callback gets called?

**Comment by weliem** [comment]
The 5 seconds delay is called the Connection  Timeout and is a lowlevel BLE thing. You can also see this number in de logs when the connection parameters are negotiated between central and peripheral. Basically it is the time they agree on to determine if a connection must be considered dropped.

In other words, there is nothing we can do about it in this library.
