### ISSUE TITLE
Blood Pressure Units Flag calculated incorrectly

### ISSUE THREAD

**Issue by imsunburnt** [weliem/blessed-android-coroutines#44]
OS version: Android 14
Device: Samsung A52
Blessed-android-coroutines: 0.4.2

The Blood Pressure Units Flag is calculated incorrectly in file BloodPressureMeasurement.kt.

Suggested fix:

In file com.welie.blessedexample.BloodPressureManagement.kt line 25:
Change unit calculation 
From:

`
  val unit = if (flags and 0x01 > 0) ObservationUnit.MMHG else ObservationUnit.KPA
`

To:

`
  val unit = if (flags and 0x01 > 0) ObservationUnit.KPA else ObservationUnit.MMHG
`

Reason:

https://bitbucket.org/bluetooth-SIG/public/src/main/gss/org.bluetooth.characteristic.blood_pressure_measurement.yaml

The BloodPressureMeasurement characteristic from the YAML file defines the Blood Pressure Units Flag as follows:

>   <...>
> 
>   fields:
>     - name: Flags
>       description: |-
>         These flags define which data fields are present in the characteristic value.
>         The bits of this field are defined below.
>       values:
>         - bit: "0"
>           description: |-
>             **Blood Pressure Units Flag
>             0 = Blood pressure for Systolic, Diastolic and MAP in units of mmHg
>             1 = Blood pressure for Systolic, Diastolic and MAP in units of kPa**
> 
>   <...>
> 
> 

Verified using Omron Model BP5450.

Might this problem exist in other Blessed repositories?

**Comment by weliem** [comment]
Looks like I fixed this in the other Blessed libraries but not in this one......see for example https://github.com/weliem/blessed-kotlin/blob/main/app/src/main/java/com/example/blessed3/BloodPressureMeasurement.kt#L35

Will fix it

**Comment by weliem** [comment]
Fixed by [67ceddd](https://github.com/weliem/blessed-android-coroutines/commit/67cedddec56269e473adb595ad00b07cc9220ceb)
