### ISSUE TITLE
Question: Why use Executors.newSingleThreadExecutor() for callback tasks?

### ISSUE THREAD

**Issue by Ilyas4869** [weliem/blessed-android-coroutines#46]
Hello,

First I'd like to thank you for developping this library, it's really helpful !

I'm trying to understand the code of the library so that I rewrite the peripheralManager to use coroutines as well, since I need to use the library on a server device.

My question is why have a specific thread allocated for callbackScope in BluetoothPeripheral.kt instead of just using the IO or Default dispatchers scope? 
The internal callbacks (that call suspendCoroutine.resume()) are ensured to execute sequentially using the command queue, so why need a single thread?

Thank you a lot!

**Comment by weliem** [comment]
Hi

If you use Dispatchers you are using a thread pool. Hence there is a small risk of callbacks not executing in their sequence of creation. I have had this issue a couple of times in the past. My notifications started to arrive out of order to the app layer. Only occasionally happened but still a problem that caused my app to malfunction.

To be 100% sure that callbacks always are delivered in the right order, I use a single thread executor. But a Dispatcher with only 1 thread combined with a queue can also work.

**Comment by Ilyas4869** [comment]
It's very clear. Thank you for the quick answer and the explanation 🙏
