### ISSUE TITLE
Unreliable notifications

### ISSUE THREAD

**Issue by clemens-** [weliem/blessed-android-coroutines#9]
Hi
I have a device using a nRF52 chip that sends a notification immediately after the notification is enabled to initially populate some fields in my Android app. I noted that this is not reliable and could narrow it down to something happening on Android, as I control the nRF52 and could verify that the notification is indeed sent. There is no log entry, it just does not happen. I have 4 characteristics, but get notifications for any number between 0 and 4 when I initially connect. Later, the notifications do work.

What I tried so far:
- Delaying the observe() call all together or individually spaced for up to 2 seconds in between calls
- Delaying the response from the nRF52 in the same manner

My code to set up notifications look like that:
`private suspend fun setupAmountNotification(peripheral: BluetoothPeripheral) {
        peripheral.getCharacteristic(
            UUID.fromString(SERVICE_UUID),
            UUID.fromString(CHAR_AMOUNT_UUID)
        )?.let {
            peripheral.observe(it) {value ->
                Log.i(TAG, "Notification for amount")
                val parser = BluetoothBytesParser(value, ByteOrder.LITTLE_ENDIAN)
                runOnUiThread{
                    onAmountNotification(parser.getIntValue(FORMAT_UINT32))
                }
            }
        }
    }`

In turn, I get this log (the other observe functions are analogous):
`D/MainActivity: Peripheral eo-4095 has CONNECTED
D/BluetoothGatt: setCharacteristicNotification() - uuid: e44e1403-14b3-457c-xxxx-34bf34932966 enable: true
D/BluetoothGatt: setCharacteristicNotification() - uuid: e44e1402-14b3-457c-xxxx-34bf34932966 enable: true
D/BluetoothGatt: setCharacteristicNotification() - uuid: e44e1401-14b3-457c-xxxx-34bf34932966 enable: true
D/BluetoothGatt: setCharacteristicNotification() - uuid: e44e1404-14b3-457c-xxxx-34bf34932966 enable: true
I/MainActivity: Notification for reservoir
I/MainActivity: Notification for status`

**Comment by weliem** [comment]
Are you just missing the first notification you are expecting? And do later ones arrive normally?

If so, I might have an idea what it could be. I store the lambda for the callback after the enabling of the notification succeeded. So the is indeed a race condition if the first notification comes in immediately because the coroutine runs on a different thread.

**Comment by clemens-** [comment]
Yes, I am just missing the first one, later ones do arrive normally. So your assumption could be correct. However, I tried to delay the response of the nRF52, but this did not really result in a different behaviour. And by delay I mean values between 10 an 1000 ms. Does it really take that long to store the lambda? 
I worked around it by first reading the values manually and then wait for the notification for all subsequent values. It does work, but is less elegant than what I intended. 
Is there anything I can try to make it work? It is not really a breaking bug though.

**Comment by weliem** [comment]
Ok, let me try a fix tomorrow....

**Comment by weliem** [comment]
I released a new version (0.1.2) with a possible fix. Can you try it?

**Comment by clemens-** [comment]
Will do tonight!

**Comment by clemens-** [comment]
Works like a charm! Thank you so much for your effort and work. And quick too!

**Comment by clemens-** [comment]
Works like a charm! Thank you so much for your effort and work. And quick too!
